name       : qt6-quick3d
version    : 6.3.0
release    : 4
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtquick3d-everywhere-src-6.3.0.tar.xz : 0ad05bd1ee1f784b18220a2d2625ee8de91662c88fdc7b798662953d86eb327e
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Quick 3D module
description: |
    Qt Quick 3D provides a high-level API for creating 3D content and 3D user interfaces based on Qt Quick. Rather than using an external engine which creates syncing issues, and additional layers of abstraction, we provide extensions to the existing Qt Quick Scene Graph for spatial content, and a renderer for that extended scene graph. When using the spatial scene graph it is also possible to mix Qt Quick 2D content with 3D content.
clang      : yes
builddeps  :
    - pkgconfig(Qt6QuickTimeline)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(assimp)
rundeps    :
    - devel :
        - assimp-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
